version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile

  servicea:
    image: servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile

